#%RAML 0.8
title: Food
version: v1
baseUri: https://foodapi-dmarquezh.herokuapp.com

securitySchemes:
  - basic:
      description: |
              This API supports Basic Authentication.
              Username: usuario
              Password: 123456

      type: Basic Authentication

/usuarios:
  get:
    description:
      Retrieve all the users
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": 1,
                "nombre": "David",
                "apellidos": "Marquez Herreros",
                "email": "davidmarquez@email.com",
                "_links": {
                  "self": "/usuarios/",
                  "first": "/usuarios/?page=1",
                  "last": "/usuario/?page=1"
                  }
              }
  /{usuario_id}:
    get:
      description:
        Retrieves an user given the ID
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "id": 1,
                  "nombre": "David",
                  "apellidos": "Marquez Herreros",
                  "email": "davidmarquez@email.com"
                }
        400:
          body:
            text/plain:
              example: |
                Bad request
        404:
          body:
            text/plain:
              example: |
                Resource not found
    put:
        responses:
          204:
            body:
              text/plain:
                example: |
                    No content

          400:
                    body:
                      text/plain:
                        example: |
                          Bad request
          404:
                    body:
                      text/plain:
                        example: |
                          Resource not found
        description:
          Updates an user given the ID
    delete:
              responses:
                204:
                  body:
                    text/plain:
                      example: |
                          No content

                400:
                          body:
                            text/plain:
                              example: |
                                Bad request
                404:
                          body:
                            text/plain:
                              example: |
                                Resource not found
              description:
                Deletes an user given the ID

  /{usuario_id}/pedidos/:
    securedBy:
      - basic
    post:
      securedBy:
        - basic
      responses:
        201:
          body:
            text/plain:
              example: |
                Created
        404:
          body:
            text/plain:
              example: |
                Resource not found
  post:
    responses:
      201:
        body:
          text/plain:
            example: |
              Created
      400:
        body:
          text/plain:
            example: |
              Bad request
    securedBy:
      - basic
/recetas:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {

              }
  put:
  post:
  delete:
/ingredientes:
  get:
    description:
      Retrieve all the users
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": 1,
                "nombre": "David",
                "apellidos": "Marquez Herreros",
                "email": "davidmarquez@email.com",
                "_links": {
                  "self": "/usuarios/",
                  "first": "/usuarios/?page=1",
                  "last": "/usuario/?page=1"
                  }
              }
  /{usuario_id}:
    get:
      description:
        Retrieves an user given the ID
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "id": 1,
                  "nombre": "David",
                  "apellidos": "Marquez Herreros",
                  "email": "davidmarquez@email.com"
                }
        400:
          body:
            text/plain:
              example: |
                Bad request
        404:
          body:
            text/plain:
              example: |
                Resource not found
    put:
        responses:
          204:
            body:
              text/plain:
                example: |
                    No content

          400:
                    body:
                      text/plain:
                        example: |
                          Bad request
          404:
                    body:
                      text/plain:
                        example: |
                          Resource not found
        description:
          Updates an user given the ID
    delete:
              responses:
                204:
                  body:
                    text/plain:
                      example: |
                          No content

                400:
                          body:
                            text/plain:
                              example: |
                                Bad request
                404:
                          body:
                            text/plain:
                              example: |
                                Resource not found
              description:
                Deletes an user given the ID
/pedidos:
  get:
    description:
      Retrieve all the users
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": 1,
                "nombre": "David",
                "apellidos": "Marquez Herreros",
                "email": "davidmarquez@email.com",
                "_links": {
                  "self": "/usuarios/",
                  "first": "/usuarios/?page=1",
                  "last": "/usuario/?page=1"
                  }
              }
  /{usuario_id}:
    get:
      description:
        Retrieves an user given the ID
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "id": 1,
                  "nombre": "David",
                  "apellidos": "Marquez Herreros",
                  "email": "davidmarquez@email.com"
                }
        400:
          body:
            text/plain:
              example: |
                Bad request
        404:
          body:
            text/plain:
              example: |
                Resource not found
    put:
        responses:
          204:
            body:
              text/plain:
                example: |
                    No content

          400:
                    body:
                      text/plain:
                        example: |
                          Bad request
          404:
                    body:
                      text/plain:
                        example: |
                          Resource not found
        description:
          Updates an user given the ID
    delete:
              responses:
                204:
                  body:
                    text/plain:
                      example: |
                          No content

                400:
                          body:
                            text/plain:
                              example: |
                                Bad request
                404:
                          body:
                            text/plain:
                              example: |
                                Resource not found
              description:
                Deletes an user given the ID
/categorias:
  get:
    description:
      Retrieve all the users
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": 1,
                "nombre": "David",
                "apellidos": "Marquez Herreros",
                "email": "davidmarquez@email.com",
                "_links": {
                  "self": "/usuarios/",
                  "first": "/usuarios/?page=1",
                  "last": "/usuario/?page=1"
                  }
              }
  /{categoria_id}:
    get:
      description:
        Retrieves an user given the ID
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "id": 1,
                  "nombre": "David",
                  "apellidos": "Marquez Herreros",
                  "email": "davidmarquez@email.com"
                }
        400:
          body:
            text/plain:
              example: |
                Bad request
        404:
          body:
            text/plain:
              example: |
                Resource not found
    put:
        responses:
          204:
            body:
              text/plain:
                example: |
                    No content

          400:
                    body:
                      text/plain:
                        example: |
                          Bad request
          404:
                    body:
                      text/plain:
                        example: |
                          Resource not found
        description:
          Updates an user given the ID
        securedBy:
          - basic
    delete:
      securedBy:
        - basic
      responses:
        204:
          body:
            text/plain:
              example: |
                No content

                400:
                  body:
                    text/plain:
                      example: |
                        Bad request
                404:
                  body:
                    text/plain:
                      example: |
                        Resource not found
              description:
                Deletes an category given the ID
/comentarios:
  get:
    description:
      Retrieve all the comments
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id":1,
                "mensaje": "Comentario 1",
                "_links": {
                  "self": "/comentarios/",
                  "first": "/comentarios/?page=1",
                  "last": "/comentarios/?page=1"
                  }
              }
  /{comentario_id}:
    get:
      description:
        Retrieves a comment given the ID
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "id":1,
                  "mensaje": "Comentario 1"
                }
        400:
          body:
            text/plain:
              example: |
                Bad request
        404:
          body:
            text/plain:
              example: |
                Resource not found
    put:
        responses:
          204:
            body:
              text/plain:
                example: |
                    No content

          400:
            body:
              text/plain:
                example: |
                  Bad request
          404:
            body:
              text/plain:
                example: |
                  Resource not found
        description:
          Updates a comment given the ID
    delete:
      responses:
        204:
          body:
            text/plain:
              example: |
                No content

        400:
          body:
            text/plain:
              example: |
                Bad request
        404:
          body:
            text/plain:
              example: |
                Resource not found
              description:
                Deletes an user given the ID
