#%RAML 0.8
title: Food
version: v1
baseUri: https://foodapi-dmarquezh.herokuapp.com

securitySchemes:
  - basic:
      description: |
              This API supports Basic Authentication.
              Username: usuario
              Password: 123456

      type: Basic Authentication

/usuarios:
  get:
    description:
      Retrieve all the users
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": 1,
                "nombre": "David",
                "apellidos": "Marquez Herreros",
                "email": "davidmarquez@email.com",
                "_links": {
                  "self": "/usuarios/",
                  "first": "/usuarios/?page=1",
                  "last": "/usuario/?page=1"
                  }
              }
  /{usuario_id}:
    get:
      description:
        Retrieves an user given the ID
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "id": 1,
                  "nombre": "David",
                  "apellidos": "Marquez Herreros",
                  "email": "davidmarquez@email.com"
                }
        400:
          body:
            text/plain:
              example: |
                Bad request
        404:
          body:
            text/plain:
              example: |
                Resource not found
    put:
        responses:
          204:
            body:
              text/plain:
                example: |
                    No content

          400:
                    body:
                      text/plain:
                        example: |
                          Bad request
          404:
                    body:
                      text/plain:
                        example: |
                          Resource not found
        description:
          Updates an user given the ID
    delete:
      responses:
        204:
          body:
            text/plain:
              example: |
                No content

        400:
          body:
            text/plain:
              example: |
                Bad request
        404:
          body:
            text/plain:
              example: |
                Resource not found
              description:
                Deletes an user given the ID

  /{usuario_id}/pedidos/:
    securedBy:
      - basic
    post:
      securedBy:
        - basic
      responses:
        201:
          body:
            text/plain:
              example: |
                Created
        404:
          body:
            text/plain:
              example: |
                Resource not found
  post:
    responses:
      201:
        body:
          text/plain:
            example: |
              Created
      400:
        body:
          text/plain:
            example: |
              Bad request
    securedBy:
      - basic
/recetas:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {

              }
  post:
    securedBy:
      - basic
  /{receta_id}:
    get:
      responses:
        200:
          body:
            application/json:
              example: |
                {

                }
    delete:
      securedBy:
        - basic
    put:
      securedBy:
        - basic
  /{receta_id}/comentarios/:
    get:
      responses:
        200:
          body:
            application/json:
              example: |
                {

                }
  /{receta_id}/ingredientes/:
    get:
      responses:
        200:
          body:
            application/json:
              example: |
                {

                }
  /{receta_id}/ingredientes/{ingrediente_id}:
    get:
      responses:
        200:
          body:
            application/json:
              example: |
                {

                }
/ingredientes:
  get:
    description:
      Retrieve all the ingredients
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": 1,
                "nombre": "Aceite de oliva",
                "precio": 3,
                "_links": {
                  "self": "/ingredientes/",
                  "first": "/ingredientes/?page=1",
                  "last": "/ingredientes/?page=1"
                  }
              }
  /{usuario_id}:
    get:
      description:
        Retrieves an ingredient given the ID
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "id": 1,
                  "nombre": "Aceite de oliva",
                  "precio": 3
                }
        400:
          body:
            text/plain:
              example: |
                Bad request
        404:
          body:
            text/plain:
              example: |
                Resource not found
    put:
        responses:
          204:
            body:
              text/plain:
                example: |
                    No content

          400:
                    body:
                      text/plain:
                        example: |
                          Bad request
          404:
                    body:
                      text/plain:
                        example: |
                          Resource not found
        description:
          Updates an ingredient given the ID
    delete:
              responses:
                204:
                  body:
                    text/plain:
                      example: |
                          No content

                400:
                          body:
                            text/plain:
                              example: |
                                Bad request
                404:
                          body:
                            text/plain:
                              example: |
                                Resource not found
              description:
                Deletes an ingredient given the ID
/pedidos:
  get:
    description:
      Retrieve all the users
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": 1,
                "Cantidad": 2,
                "Precio": 6,
                "UsuarioId": 1,
                "_links": {
                  "self": "/pedidos/",
                  "first": "/pedidos/?page=1",
                  "last": "/pedidos/?page=1"
                  }
              }
  /{pedido_id}:
    get:
      description:
        Retrieves an user given the ID
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "id": 1,
                  "Cantidad": 2,
                  "Precio": 6,
                  "UsuarioId": 1
                }
        400:
          body:
            text/plain:
              example: |
                Bad request
        404:
          body:
            text/plain:
              example: |
                Resource not found
    put:
        responses:
          204:
            body:
              text/plain:
                example: |
                    No content

          400:
            body:
              text/plain:
                example: |
                  Bad request
          404:
            body:
              text/plain:
                example: |
                  Resource not found
        description:
          Updates an user given the ID
        securedBy:
          - basic
/categorias:
  get:
    description:
      Retrieve all the categories
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": 1,
                "nombre": "Carnes",
                "_links": {
                  "self": "/categorias/",
                  "first": "/categorias/?page=1",
                  "last": "/categorias/?page=1"
                  }
              }
  /{categoria_id}:
    get:
      description:
        Retrieves a category given the ID
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "id": 1,
                  "nombre": "Carnes"
                }
        400:
          body:
            text/plain:
              example: |
                Bad request
        404:
          body:
            text/plain:
              example: |
                Resource not found
    put:
        responses:
          204:
            body:
              text/plain:
                example: |
                    No content

          400:
            body:
              text/plain:
                example: |
                  Bad request
          404:
            body:
              text/plain:
                example: |
                  Resource not found
        description:
          Updates an order given the ID
        securedBy:
          - basic
    delete:
      securedBy:
        - basic
      description: Deletes a category given the ID
      responses:
        204:
          body:
            text/plain:
              example: |
                No content

        400:
          body:
            text/plain:
              example: |
                Bad request
        404:
          body:
            text/plain:
              example: |
                Resource not found

  /{categoria_id}/recetas:
    get:
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "id": 1,
                  "nombre": "Ternera con parmesano",
                  "descripcion": "Cocinas la carne y le pones parmesano",
                  "dificultad": 1,
                  "CategoriaId": 1
                  ,
                  "id": 2,
                  "nombre": "Ternera con sal",
                  "descripcion": "Cocinas la carne y le pones sal",
                  "dificultad": 1,
                  "CategoriaId": 1
                }
        400:
          body:
            text/plain:
              example: |
                Bad request
        404:
          body:
            text/plain:
              example: |
                Resource not found
/comentarios:
  get:
    description:
      Retrieve all the comments
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id":1,
                "mensaje": "Comentario 1",
                "_links": {
                  "self": "/comentarios/",
                  "first": "/comentarios/?page=1",
                  "last": "/comentarios/?page=1"
                  }
              }
  /{comentario_id}:
    get:
      description:
        Retrieves a comment given the ID
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "id":1,
                  "mensaje": "Comentario 1"
                }
        400:
          body:
            text/plain:
              example: |
                Bad request
        404:
          body:
            text/plain:
              example: |
                Resource not found
    put:
        responses:
          204:
            body:
              text/plain:
                example: |
                    No content

          400:
            body:
              text/plain:
                example: |
                  Bad request
          404:
            body:
              text/plain:
                example: |
                  Resource not found
        description:
          Updates a comment given the ID
        securedBy:
          - basic
